// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using RIIMS.Infrastructure.Data;

#nullable disable

namespace RIIMS.Infrastructure.Migrations
{
    [DbContext(typeof(RiimsDbContext))]
    [Migration("20260908152500_AddTaskAndIdleReminderPersistence")]
    partial class AddTaskAndIdleReminderPersistence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);
#pragma warning restore 612, 618
        }
    }
}
